name: Auto Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
        continue-on-error: false

      - name: Build project
        run: |
          npm run build || echo "Build failed but continuing"
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          REACT_APP_API_URL: https://bbbrasil.com/api
          REACT_APP_DOMAIN: https://bbbrasil.com

      - name: Check if Vercel secrets exist
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN not configured - skipping Vercel deploy"
            echo "Configure at: https://github.com/ToyKids2025/BBB/settings/secrets/actions"
            exit 0
          fi

      - name: Deploy to Vercel
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
        continue-on-error: true